name: test_project
description: A new Flutter project.



environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 # Service locator
  get_it: 7.6.0
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: 2.0.5
  # Functional programming thingies
  dartz: 0.10.1 
  # Remote API
  #connectivity: 3.0.6 
  http: 1.1.0
  # Local cache
  shared_preferences: 2.2.0
  cupertino_icons: 1.0.5
  internet_connection_checker: 1.0.0+1
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.2
  

 
  flutter_lints: 2.0.2 




  
  

   #fonts:
    # - family: Schyler
     #  fonts:
      #   - asset: fonts/Schyler-Regular.ttf
       #  - asset: fonts/Schyler-Italic.ttf
        #   style: italic
     #- family: Trajan Pro
      # fonts:
       #  - asset: fonts/TrajanPro.ttf
        # - asset: fonts/TrajanPro_Bold.ttf
         #  weight: 700
